spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202204b
    username: postgres
    password: postgres
  jmx:
    default-domain: ec-202204b
server:
  servlet:
    context-path: /ec-202204b
